FROM nginx
COPY dist/bon-appetit /usr/share/nginx/html
# Copy the custom Nginx configuration file into the image
COPY custom.conf /etc/nginx/conf.d/custom.conf












# WORKDIR /app
# COPY package*.json ./
# RUN npm install
# COPY . .
# CMD ["npm", "start"]
